/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimationHeader: typeof import('./src/components/AnimationHeader.vue')['default']
    AnimationHeader2: typeof import('./src/components/AnimationHeader2.vue')['default']
    Camera: typeof import('./src/components/Camera.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    KeyMapGrid: typeof import('./src/components/KeyMapGrid.vue')['default']
    KeyMapItemList: typeof import('./src/components/KeyMapItemList.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
